#!/usr/bin/env python3
"""
Write syntaxes/newtonscript.tmLanguage.json, the TextMate grammar for
NewtonScript (syntax highlighting).

The rules follow newtc's lexer (Frames/Compiler/Lexer.cc in
newton-framework): reserved words and identifiers are case-insensitive;
comments are // and /* */ (a line starting //! passes options to newtc);
strings have the escapes \\ \" \n (CR) \t and \\u<hex>...\\u runs;
characters are $a, $\\n, $\\t, $\\\\, $\\<2 hex>, $\\u<4 hex>; symbols 'name
and '|any text|; numbers are decimal, 0x hex, and reals; @n is a magic
pointer (a ROM object).

Built-in functions (highlighted when called) come from newtc itself: the
ROM's built-in function frame (@4098) plus the functions newtc adds.

Usage: scripts/make_grammar.py [path/to/newtc]   (default: bin/darwin-arm64/newtc)
"""

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
NEWTC = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "bin" / "darwin-arm64" / "newtc"
OUT = HERE / "syntaxes" / "newtonscript.tmLanguage.json"

LIST_FUNCTIONS = """
begin
  local names := [];
  foreach name, fn in @4098 do AddArraySlot(names, SPrintObject(name));
  foreach name, fn in functions do AddArraySlot(names, SPrintObject(name));
  Write(JSONStringify(names));
end;
"""

IDENT = r"[A-Za-z_][A-Za-z0-9_]*"


def builtin_functions():
    with tempfile.TemporaryDirectory() as tmp:
        script = Path(tmp) / "functions.ns"
        script.write_text(LIST_FUNCTIONS)
        out = subprocess.run([str(NEWTC), "-stubs", "quiet", "-script", str(script)],
                             capture_output=True, text=True, check=True).stdout
    names = json.loads(out[out.index("["):out.rindex("]") + 1])
    # only names that can be written without |...|; one spelling each
    seen = {}
    for name in names:
        if re.fullmatch(IDENT, name):
            seen.setdefault(name.lower(), name)
    return sorted(seen.values(), key=str.lower)


def words(*names):
    return r"(?i)\b(?:" + "|".join(names) + r")\b"


def grammar(functions):
    return {
        "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
        "name": "NewtonScript",
        "scopeName": "source.newtonscript",
        "comment": "Generated by scripts/make_grammar.py; edit that instead.",
        "patterns": [
            {"include": "#comments"},
            {"include": "#strings"},
            {"include": "#characters"},
            {"include": "#symbols"},
            {"include": "#numbers"},
            {"include": "#definitions"},
            {"include": "#keywords"},
            {"include": "#calls"},
            {"include": "#slots"},
            {"include": "#constants"},
            {"include": "#operators"},
            {"include": "#punctuation"},
        ],
        "repository": {
            "comments": {"patterns": [
                {"name": "comment.line.pragma.newtonscript", "match": r"^\s*//!.*$"},
                {"name": "comment.line.double-slash.newtonscript",
                 "begin": "//", "end": "$",
                 "beginCaptures": {"0": {"name": "punctuation.definition.comment.newtonscript"}}},
                {"name": "comment.block.newtonscript", "begin": r"/\*", "end": r"\*/",
                 "captures": {"0": {"name": "punctuation.definition.comment.newtonscript"}}},
            ]},
            "strings": {"patterns": [
                {"name": "string.quoted.double.newtonscript", "begin": '"', "end": '"',
                 "beginCaptures": {"0": {"name": "punctuation.definition.string.begin.newtonscript"}},
                 "endCaptures": {"0": {"name": "punctuation.definition.string.end.newtonscript"}},
                 "patterns": [
                     {"name": "constant.character.escape.unicode.newtonscript",
                      "match": r"\\u(?:[0-9A-Fa-f]{4})*\\u"},
                     {"name": "constant.character.escape.newtonscript", "match": r'\\[\\"nt]'},
                     {"name": "invalid.illegal.escape.newtonscript", "match": r"\\."},
                 ]},
            ]},
            "characters": {"patterns": [
                {"name": "constant.character.newtonscript",
                 "match": r"\$(?:\\u[0-9A-Fa-f]{4}|\\[0-9A-Fa-f]{2}|\\[\\nt]|[^\s\\])"},
            ]},
            "symbols": {"patterns": [
                {"name": "constant.other.symbol.newtonscript", "match": r"'\|[^|]*\|"},
                {"name": "constant.other.symbol.newtonscript", "match": r"'" + IDENT},
                {"name": "variable.other.quoted.newtonscript", "match": r"\|[^|\n]*\|"},
            ]},
            "numbers": {"patterns": [
                {"name": "constant.numeric.hex.newtonscript", "match": r"\b0[xX][0-9A-Fa-f]+\b"},
                {"name": "constant.numeric.newtonscript",
                 "match": r"(?:\b[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[eE][-+]?[0-9]+)?\b"},
                {"name": "constant.other.magic-pointer.newtonscript", "match": r"@[0-9]+\b"},
            ]},
            "keywords": {"patterns": [
                {"name": "keyword.control.newtonscript",
                 "match": words("if", "then", "else", "for", "foreach", "to", "by", "do", "in",
                                "deeply", "collect", "while", "repeat", "until", "loop", "break",
                                "return", "try", "onexception", "begin", "end", "call", "with")},
                {"name": "storage.type.newtonscript",
                 "match": words("func", "native", "local", "global", "constant")},
                {"name": "keyword.operator.word.newtonscript",
                 "match": words("and", "or", "not", "div", "mod", "exists")},
                {"name": "variable.language.newtonscript", "match": words("self", "inherited")},
                {"name": "constant.language.newtonscript", "match": words("nil", "true")},
            ]},
            "definitions": {"patterns": [
                # global Name(args) ...
                {"match": r"(?i)\b(global)\s+(" + IDENT + r")\s*(?=\()",
                 "captures": {"1": {"name": "storage.type.newtonscript"},
                              "2": {"name": "entity.name.function.newtonscript"}}},
                # Name: func(args) ... (a method in a frame)
                {"match": r"\b(" + IDENT + r")\s*(:)(?=\s*(?i:func|native)\b)",
                 "captures": {"1": {"name": "entity.name.function.newtonscript"},
                              "2": {"name": "punctuation.separator.slot.newtonscript"}}},
            ]},
            "calls": {"patterns": [
                # obj:Msg(...), obj:?Msg(...), inherited:Msg(...)
                {"match": r"(:\??)\s*(" + IDENT + r")\s*(?=\()",
                 "captures": {"1": {"name": "keyword.operator.send.newtonscript"},
                              "2": {"name": "entity.name.function.method.newtonscript"}}},
                {"name": "support.function.builtin.newtonscript",
                 "match": r"(?i)\b(?:" + "|".join(functions) + r")\b(?=\s*\()"},
                {"name": "entity.name.function.call.newtonscript",
                 "match": r"\b" + IDENT + r"(?=\s*\()"},
            ]},
            "slots": {"patterns": [
                # name: value in a frame (not :=, not :?, not a send obj:Msg(...))
                {"match": r"\b(" + IDENT + r")\s*(:)(?![=?])(?!\s*" + IDENT + r"\s*\()",
                 "captures": {"1": {"name": "variable.other.property.newtonscript"},
                              "2": {"name": "punctuation.separator.slot.newtonscript"}}},
            ]},
            "constants": {"patterns": [
                # the convention for constants: kSomething
                {"name": "constant.other.newtonscript", "match": r"\bk[A-Z][A-Za-z0-9_]*\b"},
            ]},
            "operators": {"patterns": [
                {"name": "keyword.operator.assignment.newtonscript", "match": ":="},
                {"name": "keyword.operator.string.newtonscript", "match": "&&|&"},
                {"name": "keyword.operator.bitwise.shift.newtonscript", "match": "<<|>>"},
                {"name": "keyword.operator.comparison.newtonscript", "match": "<>|<=|>=|=|<|>"},
                {"name": "keyword.operator.arithmetic.newtonscript", "match": r"[-+*/]"},
            ]},
            "punctuation": {"patterns": [
                {"name": "punctuation.separator.newtonscript", "match": "[,;]"},
                {"name": "punctuation.accessor.newtonscript", "match": r"\."},
            ]},
        },
    }


def main():
    functions = builtin_functions()
    OUT.write_text(json.dumps(grammar(functions), indent=2) + "\n")
    print(f"wrote {OUT.relative_to(HERE)}: {len(functions)} built-in functions")


if __name__ == "__main__":
    main()
