#!/usr/bin/env python3
"""
Write test/grammar/newtonscript.test.ns, the test of the NewtonScript
grammar (run with `npm run test:grammar`). Each case is a line of
NewtonScript and the scopes expected for pieces of it; this script puts the
^^^ markers under them, so the columns are always right.
"""

from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
OUT = HERE / "test" / "grammar" / "newtonscript.test.ns"
S = ".newtonscript"
U = chr(92) + "u"     # backslash u (written so, not as an escape in this file)

# (line, [(text, which occurrence (1 = first), scope), ...])
CASES = [
    ("//! -nos1", [
        ("//! -nos1", 1, "comment.line.pragma" + S)]),
    ("global Fib(n) if n < 2 then n else Fib(n - 1) + Fib(n - 2);", [
        ("global", 1, "storage.type" + S),
        ("Fib", 1, "entity.name.function" + S),
        ("if", 1, "keyword.control" + S),
        ("<", 1, "keyword.operator.comparison" + S),
        ("2", 1, "constant.numeric" + S),
        ("then", 1, "keyword.control" + S),
        ("else", 1, "keyword.control" + S),
        ("Fib", 2, "entity.name.function.call" + S),
        ("-", 1, "keyword.operator.arithmetic" + S)]),
    (r'BEGIN local s := "a\"b\\c\n' + U + '00E9' + U + r'!" & $a & $\n & $' + U + r'2022 & $\\; END;', [
        ("BEGIN", 1, "keyword.control" + S),
        ("local", 1, "storage.type" + S),
        (":=", 1, "keyword.operator.assignment" + S),
        ('"', 1, "punctuation.definition.string.begin" + S),
        (r'\"', 1, "constant.character.escape" + S),
        (r"\\", 1, "constant.character.escape" + S),
        (r"\n", 1, "constant.character.escape" + S),
        (U + "00E9" + U, 1, "constant.character.escape.unicode" + S),
        ("!", 1, "string.quoted.double" + S),
        ("&", 1, "keyword.operator.string" + S),
        ("$a", 1, "constant.character" + S),
        (r"$\n", 1, "constant.character" + S),
        ("$" + U + "2022", 1, "constant.character" + S),
        ("$\\\\", 1, "constant.character" + S),
        ("END", 1, "keyword.control" + S)]),
    ("x := {name: 'foo, sym: '|two words|, val: 0x1F, r: 1.5e3, rom: @218};", [
        ("name", 1, "variable.other.property" + S),
        ("'foo", 1, "constant.other.symbol" + S),
        ("'|two words|", 1, "constant.other.symbol" + S),
        ("0x1F", 1, "constant.numeric.hex" + S),
        ("1.5e3", 1, "constant.numeric" + S),
        ("@218", 1, "constant.other.magic-pointer" + S)]),
    ("app := {viewClickScript: func(unit) :Close(), ok: nil and true};", [
        ("viewClickScript", 1, "entity.name.function" + S),
        ("func", 1, "storage.type" + S),
        (":", 3, "keyword.operator.send" + S),
        ("Close", 1, "entity.name.function.method" + S),
        ("ok", 1, "variable.other.property" + S),
        ("nil", 1, "constant.language" + S),
        ("and", 1, "keyword.operator.word" + S),
        ("true", 1, "constant.language" + S)]),
    ("print(x); self:?Refresh(); inherited:Open(); Print(kLF);", [
        ("print", 1, "support.function.builtin" + S),
        ("self", 1, "variable.language" + S),
        (":?", 1, "keyword.operator.send" + S),
        ("Refresh", 1, "entity.name.function.method" + S),
        ("inherited", 1, "variable.language" + S),
        ("Print", 1, "support.function.builtin" + S),
        ("kLF", 1, "constant.other" + S)]),
    ("foreach slot, value in frame collect value << 2 div 3;", [
        ("foreach", 1, "keyword.control" + S),
        ("in", 1, "keyword.control" + S),
        ("collect", 1, "keyword.control" + S),
        ("<<", 1, "keyword.operator.bitwise.shift" + S),
        ("div", 1, "keyword.operator.word" + S)]),
    ('/* a block comment, "no string" */ x := |odd name|; // the end', [
        ('/* a block comment, "no string" */', 1, "comment.block" + S),
        ("|odd name|", 1, "variable.other.quoted" + S),
        ("// the end", 1, "comment.line.double-slash" + S)]),
    ("x := y.slot; if a <> b and not (c >= d) then call f with (1, 2);", [
        (".", 1, "punctuation.accessor" + S),
        ("<>", 1, "keyword.operator.comparison" + S),
        ("not", 1, "keyword.operator.word" + S),
        (">=", 1, "keyword.operator.comparison" + S),
        ("call", 1, "keyword.control" + S),
        ("with", 1, "keyword.control" + S)]),
]


def column(line, text, which):
    start = -1
    for _ in range(which):
        start = line.index(text, start + 1)
    return start


def main():
    out = ['// SYNTAX TEST "source.newtonscript" "NewtonScript syntax highlighting"',
           "// Generated by scripts/make_grammar_test.py; edit that instead.", ""]
    for line, checks in CASES:
        out.append(line)
        for text, which, scope in checks:
            col = column(line, text, which)
            if col == 0:
                # the marker line starts with "//": point from the start with <-
                out.append("// <" + "-" * len(text) + " " + scope)
            elif col == 1:
                raise SystemExit(f"can't mark column 1: {text!r} in {line!r}")
            else:
                out.append("//" + " " * (col - 2) + "^" * len(text) + " " + scope)
        out.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(HERE)}")


if __name__ == "__main__":
    main()
